### ISSUE TITLE
How to stop format run on every save?

### ISSUE THREAD

**Issue by Omega0x013** [vlang/vscode-vlang#135]
Came back on after a couple weeks to find that now whenever I try to save files, the extension is trying to format the file, only nothing happens and it just sits there saying `Saving 'arcos.v': Running 'V' Formatter (configure).` and not saving my file, despite `Editor: Format On Save` being off. I left it running while writing this and nothing has happened. The program is a basic hello world.

**Comment by Goodwine** [comment]
For what it's worth, on VSCode you can add this setting:
```json
"[v]": {
  "editor.formatOnSave": false,
}
```

**Comment by Goodwine** [comment]
In the meantime while this bug is fixed I installed [wk-j.save-and-run](https://marketplace.visualstudio.com/items?itemName=wk-j.save-and-run) and configured it like this:
```json
"saveAndRun": {
    "commands": [
        {
            "match": ".*\\.v",
            "cmd": "v fmt -w -2 ${file}",
            "isAsync": true,
        }
    ]
}
```
Unfortunately it echoes the command on the terminal which is annoying but I assume it may be for your own security (?) I couldn't see how to turn that off
