### ISSUE TITLE
Can not use VLS (Failed installing VLS.)

### ISSUE THREAD

**Issue by ken0x0a** [vlang/vscode-vlang#211]
I got an error when I tried to use VLS feature.

The error message is
```
Failed installing VLS. See output for more information.
```

And outputs are follows

```
Error: Command failed: v -prod -o /Users/username/.vmodules/bin/vls /Users/username/.vmodules/vls/cmd/vls
/Users/username/.vmodules/vls/cmd/vls/main.v:4:1: builder error: bad module definition: /Users/username/.vmodules/vls/cmd/vls/v imports module "vls" but /Users/username/.vmodules/vls/vls/ast.v is defined as module `vls.vls`
    2 | 
    3 | import cli
    4 | import vls
      | ~~~~~~~~~~
    5 | import v.vmod
    6 | import os
```

How can I fix this error and use VLS?

**Comment by nedpals** [comment]
Apparently you need to go to the VLS folder on the `.vmodules` directory and replace every instance of `import vls` with `import vls.vls` but this is not practical and advisable at all since we update VLS from time to time.

As this is not a vscode-vlang issue, we will close this issue and keep an eye instead on https://github.com/vlang/vls/issues/72. Thanks.

**Comment by ken0x0a** [comment]
@nedpals 
I tried as you suggested, and it worked.
So I created a PR, but I don't know "just replacing" was correct to do.
Some tests were failed on my mac.

Anyway, now vls works on my mac.
Thank you!
