### ISSUE TITLE
Format Document says no formatter

### ISSUE THREAD

**Issue by leighmcculloch** [vlang/vscode-vlang#212]
I have the v0.1.7 extension installed but when I choose the option to `Format Document` in VSCode it says no formatter is installed. 

I'm aware that `vfmt` exists.

**Comment by ChildishGiant** [comment]
I've looked and it seems that for some reason @leighmcculloch deleted the functions and never re implemented them? https://github.com/vlang/vscode-vlang/commit/3d6dc517d8e1f7c7efb41a5a292dd4c63238e23e

I might just roll back my own version so that I actually have these features. The readme still says the features exist but the aren't anywhere in the code so I'm guessing that's a leftover from before

**Comment by danieldaeschle** [comment]
The features are provided by vls now.

**Comment by leighmcculloch** [comment]
I have vls installed and functioning, but I guess this is an issue for the vls extension.

**Comment by ChildishGiant** [comment]
Ideally the vscode format document command would call on vls, no?

**Comment by nedpals** [comment]
@ChildishGiant that is true

**Comment by Jarred-Sumner** [comment]
I re-enabled using `v fmt` in this branch: https://github.com/vlang/vscode-vlang/compare/master...Jarred-Sumner:jarred/fix-formatter, and tweaked a couple other things (most of the diff is prettier running, not actual changes)

If you want to install the extension you can do so here: https://github.com/Jarred-Sumner/vscode-vlang/releases/download/0.1.9/vscode-vlang-0.1.9.vsix

It'd be nice to rely on vls, but it crashes often enough that falling back to `v fmt` is helpful

**Comment by nedpals** [comment]
> It'd be nice to rely on vls, but it crashes often enough that falling back to v fmt is helpful

@Jarred-Sumner Apologies if I don't understand this fully. Does that mean that vfmt will be used if the one from VLS is not recognized? If so, then it would be good to submit your patch in here :slightly_smiling_face:

**Comment by Jarred-Sumner** [comment]
> @Jarred-Sumner Apologies if I don't understand this fully. Does that mean that vfmt will be used if the one from VLS is not recognized? If so, then it would be good to submit your patch in here 🙂

> As long as vfmt and VLS wouldn't have conflicts at the same time (if VLS is recognized) then there would be no problems at all.


I misunderstood how LSP works. It doesn't seem like the vls-based formatter runs at all in VSCode (though its possible I'm just doing something wrong)

In any case, I made some changes that take inspiration from Prettier's VSCode plugin. 
- It adds a `v fmt` status bar which shows ✔️ or 🔴 that updates on format. 
- Prints logs indicating whether or not `v fmt` succeeded and, on success, brags about how fast `v fmt` is. This is in addition to LSP's feedback. 
- Click `v fmt` to show logs. If `v fmt` fails, it shows the filename:line:column along with the error message (which is just stdout from `v fmt`)
- Fixed an issue where if saving to disk happened slower than `v fmt` would start, `v fmt` would fail because the file would be empty. This makes it copy the string from the document to stdin instead of telling `v fmt` to read from the filesystem. 

Demo video -- look at the very bottom right:

https://user-images.githubusercontent.com/709451/114684909-4204ca80-9cc6-11eb-8ca3-aff3dfe9c45a.mov


I have no idea how to make this work with `vls`, but this seems pretty fast and this is kind of a fallback for "is there a syntax error in here somewhere"

Theoretically though, if do-able with vls it should be faster (particularly on Windows) because then it wouldn't spawn a new process each time. 

Happy to turn this into a PR if its a welcome change.

**Comment by danieldaeschle** [comment]
vfmt works well with the new vls

**Comment by danieldaeschle** [comment]
@nedpals  will this be the final decision?

**Comment by nedpals** [comment]
Formatting via VLS will be the final decision.
